name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # zizmor: ignore[cache-poisoning]

concurrency:
  group: release-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    permissions:
      security-events: write # required for CI workflow SARIF upload

    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    permissions:
      contents: write # required to create a GitHub Release

    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Run build - static-x86_64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-x86_64
          cp result/bin/sshd-command dist/sshd-command-x86_64

      - name: Run build - static-aarch64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-aarch64
          cp result/bin/sshd-command dist/sshd-command-aarch64

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') # Don't create a release on dispatch
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --draft \
            LICENSE \
            dist/sshd-command-x86_64 \
            dist/sshd-command-aarch64
