name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # zizmor: ignore[cache-poisoning]

concurrency:
  group: release-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    permissions:
      security-events: write # required for CI workflow SARIF upload

    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    permissions:
      contents: write # required to create a GitHub Release

    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Run build - static-x86_64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-x86_64
          cp result/bin/sshd-command dist/sshd-command-x86_64

      - name: Run build - static-aarch64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-aarch64
          cp result/bin/sshd-command dist/sshd-command-aarch64

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') # Don't create a release on dispatch
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --draft \
            LICENSE \
            dist/sshd-command-x86_64 \
            dist/sshd-command-aarch64
