name: Release

on:
  push:
    tags:
      - "v*.*.*" 
  workflow_dispatch:
  workflow_call:

concurrency:
  group: release-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      security-events: write
      
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    permissions:
      contents: write

    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Run build - static-x86_64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-x86_64
          cp result/bin/sshd-command dist/sshd-command-x86_64

      - name: Run build - static-aarch64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-aarch64
          cp result/bin/sshd-command dist/sshd-command-aarch64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # Don't create a release on dispatch
        with:
          draft: true
          files: |
            LICENSE
            dist/sshd-command-x86_64
            dist/sshd-command-aarch64
