name: Release

on:
  push:
    tags:
      - "v*.*.*" 
  workflow_dispatch: # zizmor: ignore[cache-poisoning]

concurrency:
  group: release-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    permissions:
      security-events: write
      
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    permissions:
      contents: write

    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@754537aaedb35f72ab11a60cc162c49ef3016495 # v31

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@def9f5a5c6a6b8751c0534e8813a5d0ad2635660 # v11

      - name: Run build - static-x86_64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-x86_64
          cp result/bin/sshd-command dist/sshd-command-x86_64

      - name: Run build - static-aarch64
        run: |
          mkdir -p dist/
          nix build --print-build-logs .#static-aarch64
          cp result/bin/sshd-command dist/sshd-command-aarch64

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
        if: startsWith(github.ref, 'refs/tags/') # Don't create a release on dispatch
        with:
          draft: true
          files: |
            LICENSE
            dist/sshd-command-x86_64
            dist/sshd-command-aarch64
